apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website
  labels:
    app: simple-website
spec:
  replicas: 2 # Number of pods to run
  selector:
    matchLabels:
      app: simple-website
  template:
    metadata:
      labels:
        app: simple-website
    spec:
      containers:
      - name: simple-website
        image: sekovv/my-web-app:latest # Replace with your image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-website-service
spec:
  selector:
    app: simple-website
  ports:
  - protocol: TCP
    port: 80 # Service port
    targetPort: 80 # Container port
  type: NodePort # Change to LoadBalancer for cloud environments